config/routes.rb
Rails.application.routes.draw do

  get 'users/downgrade'

  devise_for :users
  resources :wikis
  resources :charges, only: [:new, :create]
  resources :collaborators, only: [:create, :destroy]

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/amount.rb
class Amount < ApplicationRecord
  def self.default
    15_00
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis
  has_many :collaborators, dependent: :destroy
  after_initialize :init

  def init
    self.role ||= :standard
  end

  enum role: [:standard, :admin, :premium]

  def upgrade
    self.role = :premium
  end

  def downgrade
    self.standard!
  end

  def collaborator_for(wiki)
    collaborators.where(wiki_id: wiki.id).first
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )

   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: 1500,
     currency: 'usd'
   )

   current_user.premium!

   flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   redirect_to edit_user_registration_path # or wherever

   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
 end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    @collaborator = Collaborator.new(collaborator_params)
    authorize @collaborator
    @collaborator.save

    if @collaborator.save
      flash[:notice] = "Collaborator added."
    else
      flash[:alert] = "Error adding collaborator."
    end

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @collaborator = Collaborator.find_by(user_id: params[:user_id], wiki_id: params[:wiki_id])
    authorize @collaborator

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed."
    else
      flash[:alert] = "Collaborator removal failed."
    end

    redirect_back(fallback_location: root_path)
  end

  private

  def collaborator_params
    params.permit(:user_id, :wiki_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def downgrade
    current_user.standard!

    @wikis.each do |w|
      if w.private
        w.private = false
        w.save!
      end
    end

    if @user.save
      flash[:notice] = "You've been downgraded!"
      redirect_to edit_user_registration_path
    else
      flash.now[:alert] = "Error saving topic, try again."
      render :edit
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def new
    @wiki = Wiki.new
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "wiki was saved"
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "wiki was updated."
      redirect_to [@wiki]
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true).render(content).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<!-- <%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js"
    data-key="<%= @stripe_btn_data[:key] %>"
    data-amount="<%= @stripe_btn_data[:amount] %>"
    data-description="<%= @stripe_btn_data[:description] %>" >
  </script>
<% end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WikiWawa</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if notice %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-warning"><%= alert %></p>
    <% end %>
    <div class="container">
      <ul class="nav nav-pills nav-fill">
        <li class="nav-item"><%= link_to "Home", welcome_index_path %></li>
        <li class="nav-item"><%= link_to "About", welcome_about_path %></li>
        <li class="nav-item"><%= link_to "Wikis", wikis_path %></li>
        <% if user_signed_in? %>
        <li class="pull-right nav-item">
          <span class="navbar-text">Signed in as: <strong><%= current_user.email %></strong></span>
        </li>
        <li class="pull-right nav-item">
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
        </li>
        <li class="pull-right nav-ite">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        </li>
        <% else %>
        <li class="pull-right nav-item">
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %>
        </li>
        <li class="pull-right nav-item">
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        </li>
        <% end %>
      </ul>

    <%= yield %>
    </div>
  </body>
</html>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/_form.html.erb
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter wiki name' %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <% if @wiki.persisted? %>
        <!-- <% if (current_user.admin? || current_user.premium?) && @wiki.user == current_user %> -->
        <% policy(@wiki).update? %>
          <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private %> Private wiki
            <% end %>
          </div>
        <% end %>
      <% else %>
        <% if (current_user.admin? || current_user.premium?) %>
          <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
              <%= f.check_box :private %> Private wiki
            <% end %>
          </div>
        <% end %>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-6">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
  <div class="col-md-6">
      <p>
        <strong>Markdown Preview</strong>
      </p>
      <div class="bg-light text-dark">
        <%= markdown(@wiki.body) %>
      </div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <% if @wiki.private? && (current_user.admin? || current_user.id == @wiki.user_id) %>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Email</th>
            <th scope="col">Collaborator</th>
          </tr>
        </thead>
        <tbody>
          <% User.all.each do |u| %>
          <tr>
            <th scope="row"><%= "#{u.id}" %></th>
            <td><%= "#{u.email}" %></td>
            <td>
              <% if u.collaborator_for(@wiki) %>
                <%= button_to "Remove", collaborator_path, method: :delete, params: { user_id: u.id, wiki_id: @wiki.id }, remote: true %>
              <% else %>
                <%= button_to "Add", collaborators_path, method: :post, params: { user_id: u.id, wiki_id: @wiki.id }, remote: true %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading"><%= link_to wiki.title, wiki %></h4>
            <small><%= wiki.user.email %></small>
          </div>
        </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>Create a new Wiki</h1>

<%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>


<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
</div>

<%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-success' %>
<%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>